server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
#添加dubbo配制
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.85.130:2181?backup=192.168.85.130:2182,192.168.85.130:2183


  